### ISSUE TITLE
Negative BGChange Cues Currently Broken

### ISSUE THREAD

**Issue by RimeTM** [stepmania/stepmania#1325]
No matter how far behind 0 a cue is, the command will execute as soon as ScreenGameplay begins. This makes any such cues occur far too early, especially if the cue was really close to 0 like -0.5. This is a critical issue since it affects a wide amount of content.

**Comment by shakesoda** [comment]
I don't think we ever supported negative start times? If so, when *did* it work?

**Comment by RimeTM** [comment]
From my experience, at least as far back as SM3.9 and as recent as August 29, 2016 build of SM5.1. Must admit, your question made me do a double-take because I thought this functionality was apparent from, for example, the official DDR sims and, in my case, basically everything I've done in the SM5 era.

**Comment by kyzentun** [comment]
For a couple weeks, the current beat was calculated wrong before the song started.  That may have been the cause of your problem.  It was fixed by this commit: https://github.com/stepmania/stepmania/commit/bb764a91183467cc0771cb1f7ca75c03234fe58d

I've tried a few simfiles that have a negative start beat, and they seem to be synced right.

**Comment by shakesoda** [comment]
@RimeTM: per @kyzentun's comment, try this build: http://smnightly.katzepower.com/job/Stepmania%20Nightly/128/StepManiaNightly-128.zip

**Comment by RimeTM** [comment]
Thank you; the build I was given prior to be up to theme development was from 9 days ago when the error was still present.
